# Generated by Django 4.2.20 on 2025-05-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_attendance_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='phonenumber',
            new_name='PhoneNumber',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
