# Generated by Django 4.2.20 on 2025-05-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_rename_phonenumber_attendance_phonenumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='PhoneNumber',
            new_name='phonenumber',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Price',
            field=models.IntegerField(blank=True, max_length=55, null=True),
        ),
    ]
